# Generated by Django 5.1.6 on 2025-02-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
    ]
